### ISSUE TITLE
The cursor goes back to the start while typing... 

### ISSUE THREAD

**Issue by RAJIABEFE1412** [dreampowder/flutter_social_textfield#1]
The cursor goes back to the beginning though when you type it works normal. just the cursor seems to be at the starting point.

**Comment by dreampowder** [comment]
Thanks for the feedback, yeah i've observed this behaviour too and currently looking for the solution.
If you have any suggestions or a pull request i'd be glad to hear

**Comment by ClaudeChey** [comment]
I have same issue. However, the same can happen with the Flutter default text field.

**Comment by dreampowder** [comment]
This issue has been fixed in 0.0.2. Please check with your cases too.
