### ISSUE TITLE
Cursor not moving to next line while typing Enter

### ISSUE THREAD

**Issue by sunjianan9900** [dreampowder/flutter_social_textfield#13]
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.1 21C52 darwin-arm, locale

Video：

https://user-images.githubusercontent.com/10936316/155682207-d53afbd3-98a0-452e-b9ae-e4b2ca02d368.MP4

**Comment by sunjianan9900** [comment]
Reproduction method.
1. Enter any character, enter an emoji
2. Long press the space bar to move the cursor to another position
3. Long press the space bar to move the cursor to the end, you can see that there is an extra blank character
4. Enter a new line at the end, the cursor does not enter the next line
5. Enter any character will find that in fact has been a new line

But from now on, any line break input will not work, the cursor will only go to the next line after entering the characters

复现方法：
1.输入任何字符，输入一个emoji
2.长按空格键将光标移动到其他位置
3.长按空格键将光标移动到最后，可以看到此时多出了一个空白字符
4.在最后输入换行，光标并没有进入下一行
5.输入任何字符会发现其实已经换行了

但是从现在开始，任何换行的输入将不起作用，光标只有在输入字符后会去到下一行

https://user-images.githubusercontent.com/10936316/155683632-3647fc2c-287d-4e67-afcc-a43d34d5784b.MP4

**Comment by yakitama5** [comment]
I also reproduced it when I entered Japanese.

**Comment by dreampowder** [comment]
@yakitama5 i've release an update in the recent months regarding to that, can you please check when you have time? 
Sadly somehow i haven't received any notifications about new issues uhtil now
