### ISSUE TITLE
An issue occurred after upgrading flutter 2.2.0

### ISSUE THREAD

**Issue by ClaudeChey** [dreampowder/flutter_social_textfield#2]
An issue occurred after upgrading flutter 2.2.0

    ** BUILD FAILED **
Xcode's output:
↳
4
    Invalid depfile: /Users/claude/Documents/projects/Lat/Lat/.dart_tool/flutter_build/de53b0890724bc58734a7ab9fa32f191/kernel_snapshot.d
    ../../../../.pub-cache/hosted/pub.dartlang.org/flutter_social_textfield-0.0.3/lib/controller/social_text_editing_controller.dart:94:12: Error: The method 'SocialTextEditingController.buildTextSpan' has fewer named arguments than those of overridden method 'TextEditingController.buildTextSpan'.
      TextSpan buildTextSpan({TextStyle? style, required bool withComposing}) {
               ^
    ../../../../fvm/versions/2.2.0/packages/flutter/lib/src/widgets/editable_text.dart:192:12: Context: This is the overridden method ('buildTextSpan').
      TextSpan buildTextSpan({required BuildContext context, TextStyle? style , required bool withComposing}) {
               ^
    ../../../../.pub-cache/hosted/pub.dartlang.org/flutter_social_textfield-0.0.3/lib/controller/social_text_editing_controller.dart:94:12: Error: The method 'SocialTextEditingController.buildTextSpan' doesn't have the named parameter 'context' of overridden method 'TextEditingController.buildTextSpan'.
      TextSpan buildTextSpan({TextStyle? style, required bool withComposing}) {
               ^
    ../../../../fvm/versions/2.2.0/packages/flutter/lib/src/widgets/editable_text.dart:192:12: Context: This is the overridden method ('buildTextSpan').
      TextSpan buildTextSpan({required BuildContext context, TextStyle? style , required bool withComposing}) {

**Comment by dreampowder** [comment]
hello, i will check this issue asap, thanks for your feedback

**Comment by dreampowder** [comment]
@ClaudeChey fixed in the version 0.0.4! 
please check. Thanks for your contribution.

**Comment by ClaudeChey** [comment]
@dreampowder Thank you for the quick response to the issue

**Comment by ClaudeChey** [comment]
@dreampowder Not distributed to pub.dev. Does it take time to be distributed?

**Comment by dreampowder** [comment]
@ClaudeChey looks like i got a broken connection while sending the package. it should be visible in few minutes.

**Comment by ClaudeChey** [comment]
@dreampowder  Thank you very much!! you are Best!!!

**Comment by dreampowder** [comment]
@ClaudeChey glad that i could help :D
