### ISSUE TITLE
Can we add ..ReadMore functionality with this pub

### ISSUE THREAD

**Issue by JhaNviSadhu** [dreampowder/flutter_social_textfield#20]
we are trying to show text into list view in which initially we have to show 2 lines only into cell later in detail screen we have to show entire text.

**Comment by zamirszn** [comment]
> we are trying to show text into list view in which initially we have to show 2 lines only into cell later in detail screen we have to show entire text. 

Hello I see this has been closed , were you able to achieve this with the package

**Comment by dreampowder** [comment]
hi everyone, i think it is better to keep that implementation out of the scope of this library
since this library is basically a standard TextEditingController, you can implement as the same way that you do with a normai textfield

**Comment by zamirszn** [comment]
> hi everyone, i think it is better to keep that implementation out of the scope of this library since this library is basically a standard TextEditingController, you can implement as the same way that you do with a normai textfield

oh ok, i thought this was a feature built in the package from the question @JhaNviSadhu asked , thanks alot

**Comment by zamirszn** [comment]
> hi everyone, i think it is better to keep that implementation out of the scope of this library
> since this library is basically a standard TextEditingController, you can implement as the same way that you do with a normai textfield

Sorry to bother you, is there a way I can detect user's full name ![Screenshot_2023-11-27-11-55-34-076_com.microsoft.teams.jpg](https://github.com/dreampowder/flutter_social_textfield/assets/31168776/5ccd1495-e214-4ac4-9525-36a6f4c4f4f3)
