### ISSUE TITLE
the method .subscribeToDetection is not there anymore?

### ISSUE THREAD

**Issue by SamkitJain660** [dreampowder/flutter_social_textfield#3]
the method .subscribeToDetection is not there here is some of my code-

`  void initState() {
    _subCommentController = SocialTextEditingController()..setTextStyle(DetectedType.mention, TextStyle(color: Colors.purple, backgroundColor: Colors.purple.withAlpha(50)));
  _streamSubscription =  _subCommentController.subscribeToDetection(func);
    super.initState();
  }`

and also how do i add suggestions when someone types like it comes in the example gif

**Comment by dreampowder** [comment]
i guess you figured it out @SamkitJain660 ?

**Comment by SamkitJain660** [comment]
yes i *kinda* did but can u help me with the package on discord or something i dont understand many things my discord is -
zeusking#4747

**Comment by dreampowder** [comment]
it might be hard for me to meet from discord but you can ask me about anyting form here. i will try to help as fast as i can
