### ISSUE TITLE
The cursor goes back to the start when I delete hashtags or mentions, or space.

### ISSUE THREAD

**Issue by minh-dai** [dreampowder/flutter_social_textfield#7]
I see you fixed it, but it doesn't work

**Comment by dreampowder** [comment]
Hello, i am working on this issue this week. Thanks for reporting. I'll let clpse the issue when it is done👍

**Comment by dreampowder** [comment]
version 0.0.8 is out. please check and tell me if everything is working good. 
also please check documentation if you are using default social text controller

**Comment by minh-dai** [comment]
@dreampowder thanks, you fixed it, but when I using 
textController.replaceRange(text, lastDetection.range); 
replace text to mention or hashtag, the cursor goes back to start (only the first time)
