### ISSUE TITLE
textController.replaceRange(text, lastDetection.range);  replace text to mention or hashtag, the cursor goes back to start (only the first time)

### ISSUE THREAD

**Issue by dreampowder** [dreampowder/flutter_social_textfield#8]
@dreampowder thanks, you fixed it, but when I using 
textController.replaceRange(text, lastDetection.range); 
replace text to mention or hashtag, the cursor goes back to start (only the first time)

_Originally posted by @minh-dai in https://github.com/dreampowder/flutter_social_textfield/issues/7#issuecomment-997592758_

**Comment by minh-dai** [comment]
try space after call replaceRange function, the cursor goes back to start too

**Comment by minh-dai** [comment]
hello @dreampowder any update ??

**Comment by dreampowder** [comment]
hi @minh-dai I scheduled an update for this week, I have lots of other projects to track too, sorry for delay :)

**Comment by dreampowder** [comment]
I couldn't reproduce this issue with the latest version. can you please upload a video about this?

**Comment by dreampowder** [comment]
@minh-dai this issue shuold be fixed with the latest version
